services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 091003
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  app:
    build: .
    command: uvicorn contacts.main:contacts_app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:091003@db:5432/postgres?client_encoding=UTF8
      - SECRET_KEY=q_2r-MFYMg5MrUBeYMoQftOm0Jo
      - MAIL_USERNAME=your_email@example.com
      - MAIL_PASSWORD=your_password
      - CLOUDINARY_URL=cloudinary://191677793481657:q_2r-MFYMg5MrUBeYMoQftOm0Jo@dm3fcnfwd

volumes:
  postgres_data:
  app: